spring.datasource.url=jdbc:tc:postgresql:16-alpine:///evento_celebrativo_test_${random.uuid}
spring.datasource.driver-class-name=org.testcontainers.jdbc.ContainerDatabaseDriver
spring.datasource.username=test
spring.datasource.password=test

spring.datasource.hikari.maximum-pool-size=8
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000

spring.test.database.replace=NONE
spring.h2.console.enabled=false
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=never
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration,classpath:db/test
spring.flyway.baseline-on-migrate=false
spring.flyway.validate-on-migrate=true
spring.jpa.properties.hibernate.format_sql=true

app.notifications.schedule-conflict-resolution.enabled=false
app.notifications.schedule-conflict-resolution.fixed-delay=PT15M
app.notifications.schedule-conflict-resolution.batch-size=100

logging.level.root=INFO
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN
logging.level.org.springframework.test=WARN
logging.level.org.springframework.orm.jpa=WARN
logging.level.org.springframework.transaction=WARN
logging.level.com.zaxxer.hikari=WARN
logging.level.com.eventoscelebrativos=TRACE
