spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=${DB_HIKARI_MAXIMUM_POOL_SIZE:5}
spring.datasource.hikari.minimum-idle=${DB_HIKARI_MINIMUM_IDLE:1}
spring.datasource.hikari.connection-timeout=${DB_HIKARI_CONNECTION_TIMEOUT:30000}
spring.datasource.hikari.idle-timeout=${DB_HIKARI_IDLE_TIMEOUT:600000}
spring.datasource.hikari.max-lifetime=${DB_HIKARI_MAX_LIFETIME:1800000}
spring.datasource.hikari.data-source-properties.sslmode=require

spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=never

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=false
spring.flyway.validate-on-migrate=true

logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.org.hibernate=INFO
logging.level.com.zaxxer.hikari=INFO
logging.level.com.eventoscelebrativos=DEBUG
